Exit 1 when creating the docker vm fails in setup image

diff --git a/images/docker-machine-setup/setup-aws b/images/docker-machine-setup/setup-aws
--- a/images/docker-machine-setup/setup-aws
+++ b/images/docker-machine-setup/setup-aws
@@ -38,20 +38,23 @@ docker-machine create \
     --amazonec2-security-group ${AWS_SECURITY_GROUP} \
     ${MACHINE_NAME}
 
-if [ $? == 0 ]; then
-  echo "Exporting connection info to ${MACHINE_NAME}"
-  machine-export ${MACHINE_NAME}
+if [ $? != 0]; then
+  echo "Creating docker-machine ${MACHINE_NAME} FAILED"
+  exit 1
+fi
 
-  echo "Uploading info to bucket"
-  aws --region ${AWS_DEFAULT_REGION} s3 cp ${MACHINE_NAME}.zip s3://${AWS_BUCKET}
+echo "Exporting connection info to ${MACHINE_NAME}"
+machine-export ${MACHINE_NAME}
 
-  if [ ! -z ${OPEN_TCP_PORTS} ]; then
-    echo "Opening access to docker machine on tcp ports ${OPEN_TCP_PORTS}"
-    aws ec2 authorize-security-group-ingress --group-name ${AWS_SECURITY_GROUP} --protocol tcp --port ${OPEN_TCP_PORTS} --cidr 0.0.0.0/0
-  fi
+echo "Uploading info to bucket"
+aws --region ${AWS_DEFAULT_REGION} s3 cp ${MACHINE_NAME}.zip s3://${AWS_BUCKET}
 
-  if [ ! -z ${OPEN_UDP_PORTS} ]; then
-    echo "Opening access to docker machine on udp ports ${OPEN_UDP_PORTS}"
-    aws ec2 authorize-security-group-ingress --group-name ${AWS_SECURITY_GROUP} --protocol udp --port ${OPEN_UDP_PORTS} --cidr 0.0.0.0/0
-  fi
+if [ ! -z ${OPEN_TCP_PORTS} ]; then
+  echo "Opening access to docker machine on tcp ports ${OPEN_TCP_PORTS}"
+  aws ec2 authorize-security-group-ingress --group-name ${AWS_SECURITY_GROUP} --protocol tcp --port ${OPEN_TCP_PORTS} --cidr 0.0.0.0/0
+fi
+
+if [ ! -z ${OPEN_UDP_PORTS} ]; then
+  echo "Opening access to docker machine on udp ports ${OPEN_UDP_PORTS}"
+  aws ec2 authorize-security-group-ingress --group-name ${AWS_SECURITY_GROUP} --protocol udp --port ${OPEN_UDP_PORTS} --cidr 0.0.0.0/0
 fi
